const QUIZZES = [
  {
    id: "1",
    file: "quiz1.txt",
    title: "1번 문제",
    description: "리스트 기초 문제 풀기",
    quizTitle: "파이썬 퀴즈-리스트",
  },
  {
    id: "2",
    file: "quiz2.txt",
    title: "2번 문제",
    description: "순차 문제 풀기",
    quizTitle: "파이썬 퀴즈-순차",
  },
  {
    id: "3",
    file: "quiz3.txt",
    title: "3번 문제",
    description: "선택 문제 풀기",
    quizTitle: "파이썬 퀴즈-선택",
  },
  {
    id: "4",
    file: "quiz4.txt",
    title: "4번 문제",
    description: "반복 문제 풀기",
    quizTitle: "파이썬 퀴즈-반복",
  },
  {
    id: "5",
    file: "quiz5.txt",
    title: "5번 문제",
    description: "입출력 심화 문제 풀기",
    quizTitle: "파이썬 퀴즈-입출력 심화",
  },
  {
    id: "6",
    file: "quiz6.txt",
    title: "6번 문제",
    description: "리스트 심화 문제 풀기",
    quizTitle: "파이썬 퀴즈-리스트 심화",
  },
  {
    id: "7",
    file: "quiz7.txt",
    title: "7번 문제",
    description: "순차구조 심화 문제 풀기",
    quizTitle: "파이썬 퀴즈-순차구조 심화",
  },
  {
    id: "8",
    file: "quiz8.txt",
    title: "8번 문제",
    description: "선택구조 심화 문제 풀기",
    quizTitle: "파이썬 퀴즈-선택구조 심화",
  },
  {
    id: "9",
    file: "quiz9.txt",
    title: "9번 문제",
    description: "반복구조 심화 문제 풀기",
    quizTitle: "파이썬 퀴즈-반복구조 심화",
  },
  {
    id: "0",
    file: "quiz0.txt",
    title: "0번 문제",
    description: "변수와 입출력 문제 풀기",
    quizTitle: "파이썬 퀴즈-변수와 입출력",
  },
];
